# Data Configuration
data:
  # Tickers to fetch
  universe: null  # VN30, VN100, or custom list, tui để null để tắt đi
  # custom_tickers: ['BID', 'MBB']
  custom_tickers: ['BID', 'MBB', 'ACB', 'HDB', 'STB', 'VIB', 'NAB', 'QNS', 'GEE', 'HAH', 'MSH', 'BFC', 'NTL', 'HBC', 'PDV']

  # Time range
  start_date: "2020-01-01"
  end_date: "2024-12-31"  # null means current date
  
  # Data frequency
  timeframe: "1d"  # 1d, 1h, 15m, etc.
  
  # Fields to fetch from FiinQuantX
  fields:
    - "open"
    - "high" 
    - "low"
    - "close"
    - "volume"
    - "bu"      # Buy volume (active buying)
    - "sd"      # Sell volume (active selling)
  
  # Data processing
  adjusted: true
  fill_method: "ffill"  # forward fill for prices
  volume_fill: 0        # fill volume with 0

# Feature Engineering
features:
  # Technical Indicators
  technical_indicators:
    # Trend indicators
    ema_periods: [5, 10, 20, 50]
    sma_periods: [10, 20, 50]
    macd:
      fast: 12
      slow: 26
      signal: 9
    adx_period: 14
    
    # Momentum indicators
    rsi_period: 14
    stoch_period: 14
    
    # Volatility indicators
    bollinger:
      period: 20
      std_dev: 2
    atr_period: 14
    
    # Volume indicators
    mfi_period: 14
    vwap_period: 14
  
  # Price-based features
  price_features:
    returns_periods: [1, 5, 10, 20, 60, 120]
    volatility_window: 20
    volume_ratio_window: 20
  
  # Market regime features
  regime_features:
    trend_window: 100 
    volatility_regime_window: 126

  # Trend window 100 ngày (~5 tháng) giúp model 
  # nắm được hướng đi dài hơi hơn so với 50 ngày.
  # Volatility regime 126 ngày (~6 tháng) phản ứng nhanh hơn 252 ngày (~1 năm) 
  # nhưng vẫn đủ dài để phân biệt chế độ biến động.
# Data splits
splits:
  train_ratio: 0.6
  validation_ratio: 0.2
  test_ratio: 0.2
  
  # Time-based split (walk-forward)
  min_train_samples: 500
  expanding_window: true 